backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "cards"
    label: "Karten"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Beschreibung", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string", required: false}
